package com.myapp.buckwheat.ui.settings

data class CurrencyInfo(
    val code: String,
    val name: String,
    val symbol: String
)

val worldCurrencies = listOf(
    CurrencyInfo("BERRY", "Berry", "฿"),
    CurrencyInfo("USD", "US Dollar", "$"),
    CurrencyInfo("EUR", "Euro", "€"),
    CurrencyInfo("GBP", "British Pound", "£"),
    CurrencyInfo("JPY", "Japanese Yen", "¥"),
    CurrencyInfo("CNY", "Chinese Yuan", "¥"),
    CurrencyInfo("INR", "Indian Rupee", "₹"),
    CurrencyInfo("BDT", "Bangladeshi Taka", "TK"),
    CurrencyInfo("PKR", "Pakistani Rupee", "₨"),
    CurrencyInfo("AUD", "Australian Dollar", "A$"),
    CurrencyInfo("CAD", "Canadian Dollar", "C$"),
    CurrencyInfo("CHF", "Swiss Franc", "CHF"),
    CurrencyInfo("KRW", "South Korean Won", "₩"),
    CurrencyInfo("RUB", "Russian Ruble", "₽"),
    CurrencyInfo("BRL", "Brazilian Real", "R$"),
    CurrencyInfo("MXN", "Mexican Peso", "MX$"),
    CurrencyInfo("ZAR", "South African Rand", "R"),
    CurrencyInfo("TRY", "Turkish Lira", "₺"),
    CurrencyInfo("SEK", "Swedish Krona", "kr"),
    CurrencyInfo("NOK", "Norwegian Krone", "kr"),
    CurrencyInfo("DKK", "Danish Krone", "kr"),
    CurrencyInfo("PLN", "Polish Zloty", "zł"),
    CurrencyInfo("THB", "Thai Baht", "฿"),
    CurrencyInfo("IDR", "Indonesian Rupiah", "Rp"),
    CurrencyInfo("MYR", "Malaysian Ringgit", "RM"),
    CurrencyInfo("SGD", "Singapore Dollar", "S$"),
    CurrencyInfo("PHP", "Philippine Peso", "₱"),
    CurrencyInfo("VND", "Vietnamese Dong", "₫"),
    CurrencyInfo("TWD", "Taiwan Dollar", "NT$"),
    CurrencyInfo("AED", "UAE Dirham", "AED"),
    CurrencyInfo("SAR", "Saudi Riyal", "SAR"),
    CurrencyInfo("QAR", "Qatari Riyal", "QAR"),
    CurrencyInfo("KWD", "Kuwaiti Dinar", "KWD"),
    CurrencyInfo("EGP", "Egyptian Pound", "E£"),
    CurrencyInfo("NGN", "Nigerian Naira", "₦"),
    CurrencyInfo("KES", "Kenyan Shilling", "KSh"),
    CurrencyInfo("GHS", "Ghanaian Cedi", "GH₵"),
    CurrencyInfo("CLP", "Chilean Peso", "CL$"),
    CurrencyInfo("COP", "Colombian Peso", "CO$"),
    CurrencyInfo("ARS", "Argentine Peso", "AR$"),
    CurrencyInfo("PEN", "Peruvian Sol", "S/."),
    CurrencyInfo("UAH", "Ukrainian Hryvnia", "₴"),
    CurrencyInfo("CZK", "Czech Koruna", "Kč"),
    CurrencyInfo("HUF", "Hungarian Forint", "Ft"),
    CurrencyInfo("RON", "Romanian Leu", "lei"),
    CurrencyInfo("BGN", "Bulgarian Lev", "лв"),
    CurrencyInfo("HRK", "Croatian Kuna", "kn"),
    CurrencyInfo("ISK", "Icelandic Króna", "kr"),
    CurrencyInfo("NZD", "New Zealand Dollar", "NZ$"),
    CurrencyInfo("LKR", "Sri Lankan Rupee", "Rs"),
    CurrencyInfo("MMK", "Myanmar Kyat", "K")
)
