package com.myapp.buckwheat.ui.theme

import androidx.compose.ui.graphics.Color

// Seed color for Material You fallback
val SeedColor = Color(0xFF4CAF9A)

// Custom app colors
val IncomeGreen = Color(0xFF4CAF50)
val IncomeGreenDark = Color(0xFF81C784)
val ExpenseRed = Color(0xFFE53935)
val ExpenseRedDark = Color(0xFFEF5350)
val WarningAmber = Color(0xFFFF9800)
val WarningAmberDark = Color(0xFFFFB74D)
val AdjustmentBlue = Color(0xFF5C6BC0)
val AdjustmentBlueDark = Color(0xFF7986CB)

// Calendar chart colors
val CalendarGreen = Color(0xFF4CAF50)
val CalendarAmber = Color(0xFFFF9800)
val CalendarRed = Color(0xFFE53935)
val CalendarGray = Color(0xFFBDBDBD)
val CalendarGrayDark = Color(0xFF616161)

// Light theme
val md_theme_light_primary = Color(0xFF006B5E)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF77F8E0)
val md_theme_light_onPrimaryContainer = Color(0xFF00201B)
val md_theme_light_secondary = Color(0xFF4B635D)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFCDE8E0)
val md_theme_light_onSecondaryContainer = Color(0xFF07201B)
val md_theme_light_tertiary = Color(0xFF426278)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFC7E7FF)
val md_theme_light_onTertiaryContainer = Color(0xFF001E2F)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFBFDFA)
val md_theme_light_onBackground = Color(0xFF191C1B)
val md_theme_light_surface = Color(0xFFFBFDFA)
val md_theme_light_onSurface = Color(0xFF191C1B)
val md_theme_light_surfaceVariant = Color(0xFFDBE5E0)
val md_theme_light_onSurfaceVariant = Color(0xFF3F4945)
val md_theme_light_outline = Color(0xFF6F7975)
val md_theme_light_outlineVariant = Color(0xFFBFC9C4)
val md_theme_light_inverseSurface = Color(0xFF2E3130)
val md_theme_light_inverseOnSurface = Color(0xFFEFF1EF)
val md_theme_light_inversePrimary = Color(0xFF57DBC4)
val md_theme_light_surfaceTint = Color(0xFF006B5E)

// Dark theme
val md_theme_dark_primary = Color(0xFF57DBC4)
val md_theme_dark_onPrimary = Color(0xFF003830)
val md_theme_dark_primaryContainer = Color(0xFF005047)
val md_theme_dark_onPrimaryContainer = Color(0xFF77F8E0)
val md_theme_dark_secondary = Color(0xFFB2CCC4)
val md_theme_dark_onSecondary = Color(0xFF1D352F)
val md_theme_dark_secondaryContainer = Color(0xFF344C46)
val md_theme_dark_onSecondaryContainer = Color(0xFFCDE8E0)
val md_theme_dark_tertiary = Color(0xFFAACBE3)
val md_theme_dark_onTertiary = Color(0xFF103447)
val md_theme_dark_tertiaryContainer = Color(0xFF2A4A5F)
val md_theme_dark_onTertiaryContainer = Color(0xFFC7E7FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF191C1B)
val md_theme_dark_onBackground = Color(0xFFE1E3E0)
val md_theme_dark_surface = Color(0xFF191C1B)
val md_theme_dark_onSurface = Color(0xFFE1E3E0)
val md_theme_dark_surfaceVariant = Color(0xFF3F4945)
val md_theme_dark_onSurfaceVariant = Color(0xFFBFC9C4)
val md_theme_dark_outline = Color(0xFF89938F)
val md_theme_dark_outlineVariant = Color(0xFF3F4945)
val md_theme_dark_inverseSurface = Color(0xFFE1E3E0)
val md_theme_dark_inverseOnSurface = Color(0xFF191C1B)
val md_theme_dark_inversePrimary = Color(0xFF006B5E)
val md_theme_dark_surfaceTint = Color(0xFF57DBC4)

// Alabasta theme — warm cream with coral accent
val alabasta_primary = Color(0xFFDA7756)           // coral-orange accent
val alabasta_onPrimary = Color(0xFFFFFFFF)
val alabasta_primaryContainer = Color(0xFFFFDBC9)
val alabasta_onPrimaryContainer = Color(0xFF3B1500)
val alabasta_secondary = Color(0xFF6B5C52)
val alabasta_onSecondary = Color(0xFFFFFFFF)
val alabasta_secondaryContainer = Color(0xFFF5DED3)
val alabasta_onSecondaryContainer = Color(0xFF251A12)
val alabasta_tertiary = Color(0xFF5B6D5E)
val alabasta_onTertiary = Color(0xFFFFFFFF)
val alabasta_tertiaryContainer = Color(0xFFDEE8DD)
val alabasta_onTertiaryContainer = Color(0xFF18281B)
val alabasta_error = Color(0xFFBA1A1A)
val alabasta_onError = Color(0xFFFFFFFF)
val alabasta_errorContainer = Color(0xFFFFDAD6)
val alabasta_onErrorContainer = Color(0xFF410002)
val alabasta_background = Color(0xFFF5F0E8)        // warm cream
val alabasta_onBackground = Color(0xFF1A1A1A)      // deep charcoal
val alabasta_surface = Color(0xFFF5F0E8)           // warm cream
val alabasta_onSurface = Color(0xFF1A1A1A)         // deep charcoal
val alabasta_surfaceVariant = Color(0xFFEDE5D8)
val alabasta_onSurfaceVariant = Color(0xFF4D4639)
val alabasta_outline = Color(0xFF7F7668)
val alabasta_outlineVariant = Color(0xFFD0C7B7)
val alabasta_inverseSurface = Color(0xFF33302A)
val alabasta_inverseOnSurface = Color(0xFFF8EFE5)
val alabasta_inversePrimary = Color(0xFFFFB694)
val alabasta_surfaceTint = Color(0xFFDA7756)

// Skypiea theme — celestial blue with gold accent
val skypiea_light_primary = Color(0xFF5B6FA8)           // muted indigo-blue
val skypiea_light_onPrimary = Color(0xFFFFFFFF)
val skypiea_light_primaryContainer = Color(0xFFD6E0FF)
val skypiea_light_onPrimaryContainer = Color(0xFF14204A)
val skypiea_light_secondary = Color(0xFFE8B84B)         // gold accent
val skypiea_light_onSecondary = Color(0xFF3B2E00)
val skypiea_light_secondaryContainer = Color(0xFFFFF0C7)
val skypiea_light_onSecondaryContainer = Color(0xFF241A00)
val skypiea_light_tertiary = Color(0xFF6E6A7C)
val skypiea_light_onTertiary = Color(0xFFFFFFFF)
val skypiea_light_tertiaryContainer = Color(0xFFF5EEFF)
val skypiea_light_onTertiaryContainer = Color(0xFF282536)
val skypiea_light_error = Color(0xFFBA1A1A)
val skypiea_light_onError = Color(0xFFFFFFFF)
val skypiea_light_errorContainer = Color(0xFFFFDAD6)
val skypiea_light_onErrorContainer = Color(0xFF410002)
val skypiea_light_background = Color(0xFFEEF3FF)        // light blue
val skypiea_light_onBackground = Color(0xFF1A1A2E)      // dark navy text
val skypiea_light_surface = Color(0xFFE3EAFF)           // soft blue surface
val skypiea_light_onSurface = Color(0xFF1A1A2E)         // dark navy text
val skypiea_light_surfaceVariant = Color(0xFFD8DFEE)
val skypiea_light_onSurfaceVariant = Color(0xFF3E4355)
val skypiea_light_outline = Color(0xFF6B7085)
val skypiea_light_outlineVariant = Color(0xFFBCC3D6)
val skypiea_light_inverseSurface = Color(0xFF2B2D42)
val skypiea_light_inverseOnSurface = Color(0xFFEEF0FF)
val skypiea_light_inversePrimary = Color(0xFFAFC6FF)
val skypiea_light_surfaceTint = Color(0xFF5B6FA8)

// Skypiea dark mode
val skypiea_dark_primary = Color(0xFFAFC6FF)
val skypiea_dark_onPrimary = Color(0xFF1E3060)
val skypiea_dark_primaryContainer = Color(0xFF3A4D7A)
val skypiea_dark_onPrimaryContainer = Color(0xFFD6E0FF)
val skypiea_dark_secondary = Color(0xFFE8B84B)          // gold accent (same)
val skypiea_dark_onSecondary = Color(0xFF3B2E00)
val skypiea_dark_secondaryContainer = Color(0xFF554500)
val skypiea_dark_onSecondaryContainer = Color(0xFFFFF0C7)
val skypiea_dark_tertiary = Color(0xFFD8D2E8)
val skypiea_dark_onTertiary = Color(0xFF3E3A4C)
val skypiea_dark_tertiaryContainer = Color(0xFF555164)
val skypiea_dark_onTertiaryContainer = Color(0xFFF5EEFF)
val skypiea_dark_error = Color(0xFFFFB4AB)
val skypiea_dark_onError = Color(0xFF690005)
val skypiea_dark_errorContainer = Color(0xFF93000A)
val skypiea_dark_onErrorContainer = Color(0xFFFFDAD6)
val skypiea_dark_background = Color(0xFF0D1B3E)         // deep navy
val skypiea_dark_onBackground = Color(0xFFDDE1F0)
val skypiea_dark_surface = Color(0xFF121F42)
val skypiea_dark_onSurface = Color(0xFFDDE1F0)
val skypiea_dark_surfaceVariant = Color(0xFF343850)
val skypiea_dark_onSurfaceVariant = Color(0xFFBCC3D6)
val skypiea_dark_outline = Color(0xFF868C9F)
val skypiea_dark_outlineVariant = Color(0xFF343850)
val skypiea_dark_inverseSurface = Color(0xFFDDE1F0)
val skypiea_dark_inverseOnSurface = Color(0xFF0D1B3E)
val skypiea_dark_inversePrimary = Color(0xFF5B6FA8)
val skypiea_dark_surfaceTint = Color(0xFFAFC6FF)
